name: frontend-ci
on: pull_request

jobs:
  type:
    name: Type
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm ci
      - run: npm run tsc